name: Sync to Personal Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source (org repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Sync fork
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_REPO_TOKEN }}
          script: |
            const owner = 'Kwon2do';
            const repo = 'software_WEB';
            const head_branch = 'main';
            
            console.log(`Syncing fork ${owner}/${repo} with branch ${head_branch}...`);
            
            try {
              await github.rest.repos.merge({
                owner,
                repo,
                base: head_branch,
                head: 'Software-Design-King:main',
              });
              console.log('Sync completed successfully!');
            } catch (error) {
              console.error('Error syncing fork:', error);
              core.setFailed(error.message);
            }
